image: python:3.10

cache:
  paths:
    - .venv

stages:
  - test
  - install_test
  - deploy

before_script:
  - apt-get update && apt-get install -y git ffmpeg libsm6 libxext6 build-essential git pkg-config wget libomp-dev gcovr doxygen graphviz cppcheck libeigen3-dev libboost-all-dev uuid-dev libcgal-dev libspdlog-dev ffmpeg default-jre default-jdk gcc
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lrz.de/".insteadOf "git@gitlab.lrz.de:"
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lrz.de".insteadOf "ssh://git@gitlab.lrz.de"
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - poetry install --verbose --with tests,docs
  - source .venv/bin/activate

########## Test ###############
unittest:
  stage: test
  cache: []
  script:
    - coverage run --source=./commonroad_rp -m unittest discover test
    - coverage report -m || true
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
   reports:
     coverage_report:
       coverage_format: cobertura
       path: coverage.xml

# test if pages are buildable
test_build_pages:
  stage: test
  cache: []
  allow_failure: true
  script:
    - mkdocs build
  artifacts:
    paths:
      - site
  needs: [ ]



# IMPORTANT --> Empty cache, otherwise unpredictable / racing condition during installs
test_install:
  image : python:$PYTHON_VERSIONS
  cache: []
  stage: install_test
  parallel:
    matrix:
      - PYTHON_VERSIONS: ["3.10"]
  script:
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry install
    - source .venv/bin/activate




######## Deploy ####################

# Deploy to gitlab pages
pages:
  stage: deploy
  publish: site
  only:
    - master
    - develop
  when:
    manual
  script:
    - mkdocs build
  artifacts:
    paths:
      - site
  environment:
    name: Gitlab Pages
    url: https://cps.pages.gitlab.lrz.de/commonroad/commonroad-reactive-planner/



push_to_internal_pipy_registry:
  # push the development version to the internal pipy registry https://gitlab.lrz.de/cps/reactive-planner/-/packages
  # before manually triggering the job, delete the previous package in case the version number didn't change
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "development"
      when: manual
  script:
    - poetry config repositories.gitlab ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
    - poetry build
    - poetry publish --repository gitlab -u gitlab-ci-token -p ${CI_JOB_TOKEN}

push_to_external_pipy_test_registry:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual
  script:
    - poetry config repositories.test https://test.pypi.org/legacy/
    - poetry build
    - poetry publish --repository test -u __token__ -p ${CR_PYPI_TEST_API_TOKEN}

push_to_external_pipy_release_registry:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual
  script:
    - poetry build
    - poetry publish -u __token__ -p ${CR_PYPI_RELEASE_API_TOKEN}
