site_name: CommonRoad Reactive Planner

theme:
  name: readthedocs
  logo: assets/commonroad_white150.png

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            show_root_heading: false
            heading_level: 3
            show_module_names: False
  - search

nav:
  - Introduction:
    - "Introduction": index.md

  - Examples:
      - "Minimal Examples": examples/minimal_examples.md
      - "Long Examples": examples/long_examples.md

  - API:
    - "Easy API": easy_api.md

  - API:
    - "Reactive Planner": reactive_planner.md
    - "State, Input, Trajectory": state_traj.md

